services:
- type: web
  name: app-backend
  branch: main
  env: go
  buildCommand: cd backend; go build -o app .
  startCommand: cd backend; ./app
  buildFilter:
    # build and deploy our go-backend whenever any go file changes but
    # ignore any test files
    paths:
    # changes to the frontend dir do not match this pattern
    - backend/**
    ignoredPaths:
    - backend/**/*_test.go
    - "**/*.md"
- type: web
  name: app-frontend
  branch: main
  env: static
  buildCommand: cd frontend; yarn; yarn build
  staticPublishPath: ./frontend/build/
  buildFilter:
    paths:
    # build and deploy frontend if any js file under the static dir changes
    # changes to the backend directory do not match this pattern
    - frontend/**/*.js
